const testOrder1 = {
  order_id: 98210000,
  shop_order_id: '158',
  external_order_id: '1900000ABC',
  order_source: 'allegro',
  order_source_id: '1234',
  order_source_info: '-',
  order_status_id: 85000,
  confirmed: true,
  date_confirmed: 1564503305,
  date_add: 1564501003,
  date_in_status: 1564603475,
  user_login: '',
  phone: '+48666123456',
  email: 'testmail@example.com',
  user_comments: 'Tutaj jest dodatkowe info / uwagi klienta',
  admin_comments: '',
  currency: 'PLN',
  payment_method: 'Płatność przy odbiorze',
  payment_method_cod: '1',
  payment_done: 0,
  delivery_method: 'Kurier',
  delivery_price: 19,
  delivery_package_module: 'dpd',
  delivery_package_nr: '0000154376123A',
  delivery_fullname: 'Stanisław Czelen',
  delivery_company: '',
  delivery_address: 'Warszawska 4/6',
  delivery_city: 'Wałbrzych',
  delivery_postcode: '58-301',
  delivery_country: '',
  delivery_country_code: 'PL',
  delivery_point_name: '',
  delivery_point_address: '',
  delivery_point_postcode: '',
  delivery_point_city: '',
  invoice_fullname: 'Jerzy Polak',
  invoice_company: '',
  invoice_nip: '',
  invoice_address: 'Warszawska 4/6',
  invoice_city: 'Warszawa',
  invoice_postcode: '11-111',
  invoice_country: '',
  invoice_country_code: 'PL',
  want_invoice: '0',
  extra_field_1: '',
  extra_field_2: '',
  order_page: 'https://klient.baselinker.com/98210940/s5mzf9wrz8/',
  pick_state: 0,
  pack_state: 0,
  products: [
    {
      storage: 'shop',
      storage_id: '1234',
      order_product_id: '1231231231',
      product_id: '',
      variant_id: '',
      name: 'Product Test Name',
      attributes: '',
      sku: 'PTN123',
      ean: '',
      auction_id: '1234',
      price_brutto: 1111,
      tax_rate: 23,
      quantity: 1,
      weight: 0,
    },
  ],
}

export { testOrder1 }
